[package]
name = "prod"
version = "0.1.0"
authors = ["Peter Pearson <peter.pearson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = { version = "2.2.*", features = ["json", "charset"] }
yaml-rust = "0.4"
serde_json = "1.0.*"
ssh2 = "0.9"
rpassword = "5.0"

