[package]
name = "prod"
version = "0.2.0"
authors = ["Peter Pearson"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = { version = "2.2.*", features = ["json", "charset"] }
yaml-rust = "0.4"
serde = { version = "1.0.*", features = ["derive"] }
serde_json = "1.0.*"
ssh2 = { version = "0.9", optional = true }
ssh-rs = { version = "0.4.2", optional = true, features = ["scp"] }
temp-file = { version = "0.1.7", optional = true }
rpassword = "5.0"

[features]
#default = ["openssh"]
default = ["sshrs"]
#default = []
provision = []
control = []
openssh = ["ssh2"]
sshrs = ["ssh-rs", "temp-file"]
